### ISSUE TITLE
outdated!

### ISSUE THREAD

**Issue by lordjbs** [Tisawesomeness/Minecord#20]
You are using the mcapi.ca API, which is outdated. mcapi.ca is now redirecting to https://gameapis.net/
You should look into it because I think mcapi.ca is gone soon. Docs from gameapis: https://docs.gameapis.net/docs/mc/query

**Comment by Tisawesomeness** [comment]
Fixed in commit adeb458fef10143a06a9560cae6a04c8d58e629c
