### ISSUE TITLE
MC 1.13 & snapshot items

### ISSUE THREAD

**Issue by Fox200-6** [Tisawesomeness/Minecord#31]
The new items and mobs from 1.13 and snapshots have not yet been added, and I'm already playing the snapshots for 1.13

**Comment by lordjbs** [comment]
Hello, Minecord Staff here,
Tis (the owner) will add it soon, but first when it comes out stable.

**Comment by Tisawesomeness** [comment]
Recipes and items up to 1.15 have been added. I will not add items from snapshot versions since those can change at any time.
