### ISSUE TITLE
End Crystal does not exist

### ISSUE THREAD

**Issue by SuperDoggoIsTaken** [Tisawesomeness/Minecord#32]
![image](https://user-images.githubusercontent.com/39029223/39674465-66bbbdc0-511a-11e8-8812-d10f15086a94.png)

**Comment by Tisawesomeness** [comment]
Whoops, I'll fix that as soon as possible.

**Comment by Tisawesomeness** [comment]
It's working now, thanks for the catch!
![image](https://user-images.githubusercontent.com/17386338/39884457-e6b1b6a2-5457-11e8-9bcb-15b9a7cc7d82.png)
