### ISSUE TITLE
Shield recipe not present

### ISSUE THREAD

**Issue by rodrigost23** [Tisawesomeness/Minecord#33]
`&recipe shield` just says "Combine a shield with a banner to apply the banner pattern" instead of showing the [recipe](https://minecraft.gamepedia.com/Shield#Crafting)

**Comment by Tisawesomeness** [comment]
I'll add the recipe when I create the rest of the 1.13 recipes, which should hopefully be pretty soon.

**Comment by Tisawesomeness** [comment]
This has been fixed with the recipe rewrite.
