### ISSUE TITLE
1.14 items need to be added! If you need a hand lmk

### ISSUE THREAD

**Issue by dxf** [Tisawesomeness/Minecord#37]

**Comment by mbpscruise** [comment]
This is a bot-wide, non-syntactical issue. For instance, the [anvil](https://minecraft.gamepedia.com/Anvil) is a pre-1.14.1 item. The [smoker](https://minecraft.gamepedia.com/Smoker), a new feature in Minecraft version 1.14, does not show its recipe as it should.

![image](https://user-images.githubusercontent.com/16228713/57972904-10faae80-7966-11e9-8153-77a72e3bc135.png)

**Comment by Tisawesomeness** [comment]
Items and recipes up to 1.15 have been added.
