### ISSUE TITLE
Profile command does not show overlay in the body render

### ISSUE THREAD

**Issue by cool-mist** [Tisawesomeness/Minecord#66]
Need to add ?overlay=true at the end of the uri

https://github.com/Tisawesomeness/Minecord/blob/c0ba65f2f37a2fcb186aca2fa5d3807eac855df8/src/main/java/com/tisawesomeness/minecord/mc/player/Player.java#L115-L117

https://crafatar.com/#meta-parameters

**Comment by Tisawesomeness** [comment]
I just made this change on the public bot, it will be on 1.0.0 as well. Thanks for the feedback!
