### ISSUE TITLE
main.java not found

### ISSUE THREAD

**Issue by masterofninja** [Tisawesomeness/Minecord#74]
unable to run, main file "Main.java" not found. i need help

**Comment by Tisawesomeness** [comment]
If you want to only use the bot and don't care about hosting it yourself, you can [invite the public bot](https://minecord.github.io/invite).

**If you want to self-host the bot, follow the instructions on the [master branch](https://github.com/Tisawesomeness/Minecord/tree/master#self-hosting). Self-hosters download and run a JAR file and should not get that error.**

If you want to compile from source, either to modify the code or contribute, I'd recommend using an IDE such as [IntelliJ IDEA](https://www.jetbrains.com/idea/) to view and run the source code:

1. Switch to the dev branch (or [download the source code](https://github.com/Tisawesomeness/Minecord/archive/refs/heads/dev.zip) from the dev branch).
2. Put your token in the `config.json` file as usual.
3. Navigate to `Main.java` in the IDE and press the run button.

**Comment by Tisawesomeness** [comment]
If you wold like support, please join the [support server](https://minecord.github.io/support). Closing.
